#ifndef IO__REFEREE_DEF_H
#define IO__REFEREE_DEF_H

#define REFEREE_HEAD_LEN 5
#define REFEREE_CMD_ID_LEN 2
#define REFEREE_TAIL_LEN 2

#define REFEREE_SOF 0xA5

#define REFEREE_CUSTOM_CMD_ID 0x302
#define REFEREE_KEYBOARD_AND_MOUSE_CMD_ID 0x304

#define REFEREE_DATA_START 7

#endif  // IO__REFEREE_DEF_H